"""Reply and bounce detection (FR-326, NFR-302).

FR-326 asks that bounces and replies be detected and reflected in the
opportunity status.  Two mechanisms feed one set of rules:

* **Polling**, for a connected Gmail mailbox.  ``poll_account`` reads what has
  arrived since the last cursor - through the Gmail API with the
  ``gmail.readonly`` scope Dream Job actually requests, or over IMAP with
  :mod:`imaplib` when the mailbox already grants ``https://mail.google.com/``
  (see :mod:`dreamjob.mail.gmail` for why that scope is not requested).
* **Webhooks**, for Resend, which has no mailbox to poll.

Bounces are recognised structurally, not by reading subject lines.  A delivery
failure is a delivery status notification (RFC 3464): a ``multipart/report``
whose ``report-type`` is ``delivery-status``, carrying a
``message/delivery-status`` part with ``Action:`` and ``Status:`` fields and,
usually, a ``message/rfc822`` copy of what was sent.  Parsing that gives three
things that subject matching cannot: whether the failure is permanent
(``5.x.y``) or transient (``4.x.y``), which recipient failed when a message had
several, and the original ``Message-ID`` - which is the most reliable key back
to the dispatch, because the bounce itself is a new message from a mailer
daemon and shares no headers with the reply chain.

Matching order, for both replies and bounces: ``In-Reply-To``, then every id in
``References``, then the ``Message-ID`` quoted inside a report, and only then
recipient plus subject.  The fallback is last because two applications to the
same company can share a subject.
"""

from __future__ import annotations

import email
import email.policy
import imaplib
import logging
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from email.message import EmailMessage
from email.utils import getaddresses, parsedate_to_datetime
from typing import Any

from dreamjob.config import get_settings
from dreamjob.db.connection import utcnow
from dreamjob.db.repositories import contacts as contacts_repo
from dreamjob.db.repositories import dispatch as repo
from dreamjob.mail import composer
from dreamjob.security.audit import record_audit

log = logging.getLogger(__name__)

MESSAGE_ID_RE = re.compile(r"<[^<>@\s]+@[^<>\s]+>")

#: RFC 3464 ``Action`` values that mean the message did not arrive.
FAILED_ACTIONS = {"failed", "delayed"}

#: NFR-302 - phrasings that count as an objection, in the four languages the
#: introduction e-mail is written in.  The message we send asks for exactly the
#: first entry of each language, so the common case is an exact hit; the rest
#: catch the ways people actually phrase it.
OBJECTION_PHRASES: tuple[str, ...] = (
    "no thank you", "unsubscribe", "remove me", "do not contact", "don't contact",
    "stop contacting", "opt out", "take me off",
    "liever niet", "uitschrijven", "geen interesse in dit soort", "niet meer contact",
    "graag verwijderen",
    "non merci", "désinscri", "desinscri", "ne me contactez plus", "me retirer",
    "nein danke", "abmelden", "keine weiteren", "nicht mehr kontaktieren",
)

#: Headers that mark a message as generated by a machine rather than a person.
AUTO_REPLY_HEADERS = ("auto-submitted", "x-autoreply", "x-autorespond", "x-auto-response-suppress")


@dataclass
class BounceReport:
    """The machine-readable half of a delivery status notification (RFC 3464)."""

    action: str = ""
    status: str = ""
    recipient: str = ""
    diagnostic: str = ""
    reporting_mta: str = ""
    original_message_id: str = ""

    @property
    def permanent(self) -> bool:
        """A 5.x.y status is permanent; 4.x.y is a transient deferral."""
        return self.status.startswith("5")

    @property
    def failed(self) -> bool:
        return self.action.lower() in FAILED_ACTIONS or self.status.startswith(("4", "5"))


@dataclass
class IncomingMessage:
    """One parsed inbound message, whatever transport it arrived over."""

    message_id: str = ""
    in_reply_to: str = ""
    references: list[str] = field(default_factory=list)
    from_address: str = ""
    from_name: str = ""
    to_addresses: list[str] = field(default_factory=list)
    subject: str = ""
    received_at: str = ""
    body: str = ""
    is_bounce: bool = False
    is_auto_reply: bool = False
    bounce: BounceReport | None = None
    raw_size: int = 0

    @property
    def thread_ids(self) -> list[str]:
        """Every id that could name the message this one answers, best first."""
        ids: list[str] = []
        candidates = [self.in_reply_to]
        if self.bounce:
            candidates.append(self.bounce.original_message_id)
        candidates.extend(reversed(self.references))
        for candidate in candidates:
            if candidate and candidate not in ids:
                ids.append(candidate)
        return ids


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _header_ids(value: str | None) -> list[str]:
    return MESSAGE_ID_RE.findall(value or "")


def _first_address(value: str | None) -> tuple[str, str]:
    for name, addr in getaddresses([value or ""]):
        if addr:
            return addr.strip().lower(), name.strip()
    return "", ""


def _received_at(message: EmailMessage) -> str:
    raw = message.get("Date")
    if raw:
        try:
            return parsedate_to_datetime(raw).astimezone(UTC).isoformat(timespec="seconds")
        except (TypeError, ValueError):
            pass
    return utcnow()


def _plain_body(message: EmailMessage, limit: int = 20_000) -> str:
    """The readable text, preferring text/plain and falling back to stripped HTML."""
    try:
        part = message.get_body(preferencelist=("plain", "html"))
    except Exception:  # noqa: BLE001 - malformed MIME must not stop the poll
        part = None
    if part is None:
        return ""
    try:
        content = part.get_content()
    except Exception:  # noqa: BLE001 - unknown charset
        payload = part.get_payload(decode=True) or b""
        content = payload.decode("utf-8", errors="replace")
    if part.get_content_subtype() == "html":
        content = re.sub(r"<[^>]+>", " ", content)
    return re.sub(r"[ \t]+", " ", str(content)).strip()[:limit]


def parse_delivery_status(message: EmailMessage) -> BounceReport | None:
    """Read the RFC 3464 report parts, not the prose (FR-326).

    ``message/delivery-status`` is a sequence of RFC 822-style field blocks: one
    per-message block, then one per-recipient block carrying ``Action`` and
    ``Status``.  ``message/rfc822`` (or ``text/rfc822-headers``) holds what was
    sent, which is where the original ``Message-ID`` comes from.
    """
    content_type = message.get_content_type()
    report_type = str(message.get_param("report-type", "") or "").lower()
    if content_type != "multipart/report" and report_type != "delivery-status":
        return None

    report = BounceReport()
    for part in message.walk():
        subtype = part.get_content_type()
        if subtype == "message/delivery-status":
            for block in part.get_payload():
                if not hasattr(block, "get"):
                    continue
                action = str(block.get("Action", "") or "")
                if action:
                    report.action = action.strip().lower()
                status = str(block.get("Status", "") or "").strip()
                if status:
                    report.status = status
                recipient = block.get("Final-Recipient") or block.get("Original-Recipient")
                if recipient:
                    report.recipient = str(recipient).split(";")[-1].strip().lower()
                diagnostic = block.get("Diagnostic-Code")
                if diagnostic:
                    report.diagnostic = str(diagnostic).strip()[:500]
                mta = block.get("Reporting-MTA")
                if mta:
                    report.reporting_mta = str(mta).split(";")[-1].strip()
        elif subtype in ("message/rfc822", "text/rfc822-headers"):
            original = part.get_payload(0) if part.is_multipart() else None
            if original is None:
                try:
                    original = email.message_from_string(
                        str(part.get_payload()), policy=email.policy.default
                    )
                except Exception:  # noqa: BLE001
                    original = None
            if original is not None:
                ids = _header_ids(original.get("Message-ID"))
                if ids:
                    report.original_message_id = ids[0]
                if not report.recipient:
                    report.recipient, _ = _first_address(original.get("To"))
    return report if (report.action or report.status or report.original_message_id) else None


def parse_message(raw: bytes) -> IncomingMessage:
    """Parse one RFC 822 message into the fields FR-326 matches and records on."""
    message: EmailMessage = email.message_from_bytes(raw, policy=email.policy.default)
    from_address, from_name = _first_address(message.get("From"))
    to_addresses = [a for _, a in getaddresses([message.get("To", "")]) if a]

    bounce = parse_delivery_status(message)
    incoming = IncomingMessage(
        message_id=(_header_ids(message.get("Message-ID")) or [""])[0],
        in_reply_to=(_header_ids(message.get("In-Reply-To")) or [""])[0],
        references=_header_ids(message.get("References")),
        from_address=from_address,
        from_name=from_name,
        to_addresses=[a.lower() for a in to_addresses],
        subject=str(message.get("Subject", "") or ""),
        received_at=_received_at(message),
        body=_plain_body(message),
        bounce=bounce,
        is_bounce=bool(bounce and bounce.failed),
        raw_size=len(raw),
    )
    incoming.is_auto_reply = _looks_automatic(message, incoming)
    return incoming


def _looks_automatic(message: EmailMessage, incoming: IncomingMessage) -> bool:
    """Out-of-office and vacation replies, which must not clear a follow-up."""
    if incoming.is_bounce:
        return True
    for header in AUTO_REPLY_HEADERS:
        value = str(message.get(header, "") or "").lower()
        if value and value != "no":
            return True
    if str(message.get("Precedence", "") or "").lower() in ("bulk", "auto_reply", "junk"):
        return True
    return False


def _sentence_pattern(template: str) -> re.Pattern[str]:
    """Match one of our own objection sentences, whatever address it names."""
    joined = r"\S+".join(re.escape(part) for part in template.split("{address}"))
    # re.escape() escapes spaces too, and the sentence is line-wrapped when it
    # is sent, so every run of (escaped) whitespace becomes a whitespace class.
    return re.compile(re.sub(r"(?:\\?\s)+", r"\\s+", joined), re.IGNORECASE)


#: The sentence NFR-302 puts at the foot of every message we send.  A reply
#: quotes it back at us, so it has to be removed before the reply is read for
#: an objection - otherwise every quoted reply looks like one.
OWN_OBJECTION_SENTENCES: tuple[re.Pattern[str], ...] = tuple(
    _sentence_pattern(template) for template in composer.OBJECTION_SENTENCE.values()
)

#: Where a reply stops being the sender's own words and becomes the message
#: they are answering: the quote markers the common clients write.
QUOTED_LINE = re.compile(
    r"^\s*(?:>"
    r"|-{2,}\s*original message"
    r"|_{5,}"
    r"|on\b.{0,160}\bwrote:"
    r"|(?:op|le|am)\b.{0,160}\b(?:schreef|geschreven|écrit|schrieb):"
    r"|(?:from|van|de|von|sent|verzonden|gesendet|envoyé|to|aan|à)\s*:"
    r")",
    re.IGNORECASE,
)


def own_words(text: str) -> str:
    """What the sender actually typed, with the message they quoted removed.

    Quoted lines are dropped rather than everything below the first one, so a
    reply written underneath the quotation - the normal style in half of
    Europe - is still read (NFR-302, FR-326).
    """
    kept = [line for line in (text or "").splitlines() if not QUOTED_LINE.match(line)]
    body = "\n".join(kept)
    # A client that quotes without markers, or that sent HTML whose tags have
    # been stripped, leaves the sentence itself in place; remove that too.
    for pattern in OWN_OBJECTION_SENTENCES:
        body = pattern.sub(" ", body)
    return body.strip()


def is_objection(text: str) -> bool:
    """NFR-302: did the recipient ask not to be contacted again?

    Read on the sender's own words only.  Blocking a contact is permanent and
    applies to every job seeker, so a phrase that is only present because the
    reply quotes what we sent must not trigger it.
    """
    lowered = own_words(text).lower()
    return any(phrase in lowered for phrase in OBJECTION_PHRASES)


# ---------------------------------------------------------------------------
# Matching and recording (FR-326)
# ---------------------------------------------------------------------------


def match_dispatch(job_seeker_id: str, incoming: IncomingMessage) -> dict | None:
    """Message-ID chain first, recipient plus subject only as a fallback."""
    match = repo.dispatch_by_message_ids(job_seeker_id, incoming.thread_ids)
    if match:
        return match
    # A bounce comes from the mailer daemon, so the address to look up is the
    # one that failed, not the sender of the report.
    address = (
        (incoming.bounce.recipient if incoming.bounce else "") or incoming.from_address
    )
    if not address:
        return None
    return repo.dispatch_by_recipient(job_seeker_id, address, subject=incoming.subject)


def record_incoming(
    job_seeker_id: str, incoming: IncomingMessage, *, source: str = "poll"
) -> dict:
    """Apply one inbound message to the send log.  Idempotent on Message-ID."""
    if incoming.message_id and repo.reply_exists(job_seeker_id, incoming.message_id):
        return {"status": "duplicate", "message_id": incoming.message_id}

    match = match_dispatch(job_seeker_id, incoming)
    dispatch_id = match["id"] if match else None
    chain = incoming.thread_ids

    if incoming.is_bounce:
        outcome = _apply_bounce(job_seeker_id, incoming, match, source=source)
    else:
        outcome = _apply_reply(job_seeker_id, incoming, match, source=source)

    reply_id = repo.record_reply(
        job_seeker_id,
        {
            "dispatch_id": dispatch_id,
            "from_address": incoming.from_address,
            "subject": incoming.subject,
            "body": incoming.body,
            "received_at": incoming.received_at,
            "message_id": incoming.message_id,
            "in_reply_to": incoming.in_reply_to or (chain[0] if chain else None),
            "classification": outcome["classification"],
        },
    )
    outcome["incoming_reply_id"] = reply_id
    outcome["dispatch_id"] = dispatch_id
    return outcome


def _apply_bounce(
    job_seeker_id: str, incoming: IncomingMessage, match: dict | None, *, source: str
) -> dict:
    report = incoming.bounce or BounceReport()
    permanent = report.permanent
    detail = {
        "source": source,
        "action": report.action,
        "status": report.status,
        "diagnostic": report.diagnostic,
        "reporting_mta": report.reporting_mta,
        "failed_recipient": report.recipient,
        "permanent": permanent,
    }
    if match:
        repo.update_dispatch(
            match["id"],
            {
                # A 4.x.y deferral is not a failure yet: the sending MTA is still
                # retrying, so the dispatch keeps its status and records the detail.
                **({"delivery_status": "bounced"} if permanent else {}),
                "bounce_detected_at": incoming.received_at or utcnow(),
                "delivery_detail": detail,
            },
        )
        repo.notify(
            job_seeker_id,
            "reply",
            f"Delivery failed: {match.get('recipient_email')}",
            report.diagnostic or report.status,
            {"dispatch_id": match["id"], "permanent": permanent},
            dedup_key=f"bounce:{match['id']}",
        )
        record_audit(
            "dispatch.bounced",
            "dispatch",
            match["id"],
            seeker_id=job_seeker_id,
            actor="system",
            detail=detail,
        )
    else:
        log.info("Bounce for %s did not match a dispatch", report.recipient or incoming.subject)
    return {
        "status": "bounced" if permanent else "deferred",
        "classification": "bounce",
        "detail": detail,
    }


def _apply_reply(
    job_seeker_id: str, incoming: IncomingMessage, match: dict | None, *, source: str
) -> dict:
    classification = "auto_reply" if incoming.is_auto_reply else None
    objected = False

    if match and not incoming.is_auto_reply:
        repo.update_dispatch(
            match["id"],
            {
                "reply_detected_at": incoming.received_at or utcnow(),
                "delivery_status": "delivered",
            },
        )
        repo.notify(
            job_seeker_id,
            "reply",
            f"Reply from {incoming.from_name or incoming.from_address}",
            incoming.subject,
            {"dispatch_id": match["id"], "from": incoming.from_address},
        )
        record_audit(
            "dispatch.replied",
            "dispatch",
            match["id"],
            seeker_id=job_seeker_id,
            actor="system",
            detail={"from": incoming.from_address, "source": source},
        )

    # NFR-302: an objection blocks the address permanently and for every job
    # seeker, so it is honoured the moment it is read - not when someone gets
    # round to reviewing the reply.
    if incoming.from_address and not incoming.is_auto_reply and is_objection(incoming.body):
        contacts_repo.record_objection(
            incoming.from_address,
            reason="Objection received by e-mail reply",
            source="reply",
        )
        classification = "objection"
        objected = True
        record_audit(
            "contact.objected",
            "contact",
            incoming.from_address,
            seeker_id=job_seeker_id,
            actor="system",
            detail={"source": "reply", "dispatch_id": match["id"] if match else None},
        )

    return {
        "status": "objection"
        if objected
        else ("auto_reply" if incoming.is_auto_reply else "reply"),
        "classification": classification,
        "matched": bool(match),
    }


def apply_provider_event(event: dict, *, delivery_id: str, provider: str) -> dict:
    """Apply one webhook event (Resend) to the send log (FR-326).

    Idempotent: the provider retries until it is acknowledged, so the delivery
    id is recorded first and a replay returns without touching the dispatch.
    """
    event_id = delivery_id or str(event.get("provider_message_id") or utcnow())
    if repo.webhook_event_seen(event_id):
        return {"status": "duplicate", "event_id": event_id}

    # The webhook carries no session, so the dispatch has to identify its own
    # job seeker.  The provider's own send id - stored as ``thread_id`` when the
    # message went out - is ours and is unique, so it is the only key used here;
    # matching on a header would mean searching across job seekers (FR-344).
    match = None
    if event.get("provider_message_id"):
        match = repo.dispatch_by_provider_message_id(str(event["provider_message_id"]))

    repo.record_webhook_event(
        event_id,
        provider=provider,
        event_type=str(event.get("event_type") or "unknown"),
        provider_message_id=event.get("provider_message_id"),
        recipient=event.get("recipient"),
        dispatch_id=match["id"] if match else None,
        payload=event.get("raw"),
    )

    if match is None:
        log.info("%s event %s matched no dispatch", provider, event.get("event_type"))
        return {"status": "unmatched", "event_type": event.get("event_type")}

    seeker_id = match["job_seeker_id"]
    status = event.get("status")
    values: dict[str, Any] = {"delivery_detail": {k: v for k, v in event.items() if k != "raw"}}
    if status:
        values["delivery_status"] = status
    if status == "bounced":
        values["bounce_detected_at"] = utcnow()
    repo.update_dispatch(match["id"], values)

    if status == "bounced":
        repo.notify(
            seeker_id,
            "reply",
            f"Delivery failed: {match.get('recipient_email')}",
            event.get("reason"),
            {"dispatch_id": match["id"], "event_type": event.get("event_type")},
            dedup_key=f"bounce:{match['id']}",
        )
        # A spam complaint is an objection in everything but name (NFR-302).
        if event.get("event_type") == "email.complained" and match.get("recipient_email"):
            contacts_repo.record_objection(
                match["recipient_email"], reason="Spam complaint via Resend", source="unsubscribe"
            )
    record_audit(
        f"dispatch.{status or 'event'}",
        "dispatch",
        match["id"],
        seeker_id=seeker_id,
        actor="system",
        detail={"provider": provider, "event_type": event.get("event_type")},
    )
    repo.mark_webhook_processed(event_id, match["id"])
    return {"status": status or "recorded", "dispatch_id": match["id"]}


# ---------------------------------------------------------------------------
# Polling a connected mailbox (FR-326)
# ---------------------------------------------------------------------------


def poll_account(account: dict, *, max_messages: int = 100) -> dict:
    """Read what has arrived in one mailbox since the last cursor.

    Chooses the transport the mailbox can actually use: IMAP when the granted
    scopes include full mailbox access, otherwise the Gmail API, which is what
    the ``gmail.readonly`` scope Dream Job requests supports.
    """
    from dreamjob.mail.gmail import IMAP_SCOPE, GmailBackend  # noqa: PLC0415

    if account.get("backend") != "gmail_oauth":
        return {
            "account_id": account.get("id"),
            "polled": 0,
            "skipped": f"{account.get('backend')} has no mailbox to poll; it reports by webhook",
        }

    backend = GmailBackend(account)
    scopes = set(str(account.get("scopes") or "").split())
    try:
        if IMAP_SCOPE in scopes:
            result = poll_imap(account, backend, max_messages=max_messages)
        else:
            result = poll_gmail_api(account, backend, max_messages=max_messages)
    except Exception as exc:  # noqa: BLE001 - a failing mailbox must not stop the job
        log.exception("Polling mailbox %s failed", account.get("address"))
        repo.save_poll_state(account["id"], {"last_error": str(exc)[:500]})
        return {"account_id": account["id"], "polled": 0, "error": str(exc)[:500]}
    return result


def poll_gmail_api(account: dict, backend: Any, *, max_messages: int = 100) -> dict:
    """Poll with ``gmail.readonly``: search since the cursor, fetch raw, apply."""
    state = repo.get_poll_state(account["id"]) or {}
    since = state.get("last_polled_at")
    query = "-in:sent -in:chats"
    if since:
        # Gmail's `after:` is whole-second epoch and is inclusive; a minute of
        # overlap costs nothing because record_incoming is idempotent.
        epoch = int(datetime.fromisoformat(since).timestamp()) - 60
        query = f"{query} after:{epoch}"
    else:
        query = f"{query} newer_than:7d"

    ids = backend.list_message_ids(query, max_results=max_messages)
    outcomes = {"reply": 0, "bounced": 0, "deferred": 0, "auto_reply": 0, "objection": 0}
    seen = 0
    for gmail_id in ids:
        raw = backend.fetch_raw(gmail_id)
        incoming = parse_message(raw)
        if incoming.from_address == str(account.get("address", "")).lower():
            continue
        result = record_incoming(account["job_seeker_id"], incoming, source="gmail_api")
        seen += 1
        if result["status"] in outcomes:
            outcomes[result["status"]] += 1

    repo.save_poll_state(
        account["id"],
        {
            "last_polled_at": utcnow(),
            "last_error": None,
            "messages_seen": int(state.get("messages_seen") or 0) + seen,
        },
    )
    return {"account_id": account["id"], "polled": seen, "transport": "gmail_api", **outcomes}


def _xoauth2_string(address: str, access_token: str) -> str:
    return f"user={address}\x01auth=Bearer {access_token}\x01\x01"


def poll_imap(
    account: dict,
    backend: Any,
    *,
    max_messages: int = 100,
    password: str | None = None,
) -> dict:
    """Poll over IMAP with :mod:`imaplib`, resuming from the stored UID.

    UIDVALIDITY is checked first: when the server changes it the stored UIDs no
    longer mean anything and the cursor has to be dropped rather than trusted,
    which is the difference between resuming and silently reading nothing ever
    again.
    """
    settings = get_settings()
    state = repo.get_poll_state(account["id"]) or {}
    address = str(account.get("address") or "")

    client = imaplib.IMAP4_SSL(settings.imap_host, settings.imap_port)
    try:
        if password:
            client.login(address, password)
        else:
            token = backend.access_token()
            client.authenticate(
                "XOAUTH2", lambda _challenge: _xoauth2_string(address, token).encode()
            )
        folder = state.get("folder") or "INBOX"
        client.select(folder, readonly=True)

        typ, data = client.status(folder, "(UIDVALIDITY)")
        validity = ""
        if typ == "OK" and data:
            match = re.search(rb"UIDVALIDITY (\d+)", data[0] or b"")
            validity = match.group(1).decode() if match else ""

        last_uid = int(state.get("last_uid") or 0)
        if validity and state.get("uid_validity") and validity != state["uid_validity"]:
            log.info("UIDVALIDITY changed on %s; restarting the cursor", address)
            last_uid = 0

        typ, data = client.uid("SEARCH", None, f"UID {last_uid + 1}:*")
        uids = [int(u) for u in (data[0] or b"").split() if int(u) > last_uid][:max_messages]

        outcomes = {"reply": 0, "bounced": 0, "deferred": 0, "auto_reply": 0, "objection": 0}
        seen = 0
        highest = last_uid
        for uid in uids:
            typ, payload = client.uid("FETCH", str(uid), "(RFC822)")
            if typ != "OK" or not payload or not isinstance(payload[0], tuple):
                continue
            incoming = parse_message(payload[0][1])
            highest = max(highest, uid)
            if incoming.from_address == address.lower():
                continue
            result = record_incoming(account["job_seeker_id"], incoming, source="imap")
            seen += 1
            if result["status"] in outcomes:
                outcomes[result["status"]] += 1

        repo.save_poll_state(
            account["id"],
            {
                "folder": folder,
                "uid_validity": validity or state.get("uid_validity"),
                "last_uid": highest,
                "last_polled_at": utcnow(),
                "last_error": None,
                "messages_seen": int(state.get("messages_seen") or 0) + seen,
            },
        )
        return {"account_id": account["id"], "polled": seen, "transport": "imap", **outcomes}
    finally:
        try:
            client.logout()
        except (OSError, imaplib.IMAP4.error):  # pragma: no cover - best effort
            pass


def poll_all(job_seeker_id: str | None = None, *, max_messages: int = 100) -> list[dict]:
    """Poll every connected mailbox; one failure does not stop the others."""
    accounts = repo.accounts_to_poll("gmail_oauth")
    if job_seeker_id:
        accounts = [a for a in accounts if a["job_seeker_id"] == job_seeker_id]
    return [poll_account(a, max_messages=max_messages) for a in accounts]
